version: '3'

services:
    maria-db:
        container_name: lot-maria-db
        build: .\Build\mariadb\10.4
        ports: 
          - 3306:3306
        env_file:
          - .\.env
        environment:
          - MYSQL_DATABASE=lot-maria-db
          - MYSQL_ALLOW_EMPTY_PASSWORD=no
          - MYSQL_ROOT_USER=root
    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - 8081:8080
            - 81:80
        volumes:
            - ./Build/swagger/openapi.json:/openapi.json
        environment:
            SWAGGER_JSON: /openapi.json
        container_name: lot-swagger-ui